tidy

diff --git a/.github/workflows/quick-update.yml b/.github/workflows/quick-update.yml
--- a/.github/workflows/quick-update.yml
+++ b/.github/workflows/quick-update.yml
@@ -15,11 +15,6 @@ on:
         default: 'Available'
         required: true
         options: [ 'Available', 'Removed', 'Developer', 'Joke', "N/A" ]
-      ar_command:
-        description: '+/- commands'
-        type: boolean
-        default: true
-        required: true
       common:
         description: 'Is common'
         type: boolean
@@ -93,37 +88,41 @@ jobs:
           echo "path=$path" >> $GITHUB_OUTPUT
           echo "full_path=$full_path" >> $GITHUB_OUTPUT
           echo "change=$change" >> $GITHUB_OUTPUT
-      - name: +/-
-        if: ${{ inputs.ar_command == true }}
+      - name: Modify files
         run: |
           path='${{ steps.data.outputs.path }}'
           full_path='${{ steps.data.outputs.full_path }}'
           change='${{ steps.data.outputs.change }};'
           i=1
-          if [[ $change = *=* ]]; then
-            echo '[Error]Invalid syntax.'
-            exit 1
-          fi
           while ((1==1)); do
             cmd=`echo $change | cut -d ';' -f $i`
             if ! [ $cmd ]; then
               break
             else
-              if [[ $cmd = -* ]]; then
-                mode='-'
-                cmd=${cmd:1}
-              else
-                mode='+'
-                if [[ $cmd = +* ]]; then
+              if [[ $cmd = *=* ]]; then
+                mode='='
+                if [[ $cmd = /* ]]; then
                   cmd=${cmd:1}
                 fi
+                cmd=${cmd//=\//=}
+                echo "=== Run ($cmd) ==="
+              else
+                if [[ $cmd = -* ]]; then
+                  mode='-'
+                  cmd=${cmd:1}
+                else
+                  mode='+'
+                  if [[ $cmd = +* ]]; then
+                    cmd=${cmd:1}
+                  fi
+                fi
+                if [[ $cmd = /* ]]; then
+                  cmd=${cmd:1}
+                fi
+                echo "=== Run ($mode$cmd) ==="
               fi
-              if [[ $cmd = /* ]]; then
-                cmd=${cmd:1}
-              fi
-              echo "=== Run ($mode$cmd) ==="
-              if [[ path = */where/* ]]; then
-                if [ $mode = '-' ]; then
+              if [[ $path = */where/* ]]; then
+                if [ $mode != '+' ]; then
                   path=$full_path
                 fi
               fi
@@ -134,62 +133,23 @@ jobs:
                   exit 1
                 fi
                 cp $file $file-1
-                if [ $mode = '+' ]; then
-                  echo $cmd >> $file
-                else
-                  sed "s/^$cmd$//g" $file | sed '/^$/d' > $file-2
+                if [ $mode = '=' ]; then
+                  from=`echo $cmd | cut -d '=' -f 1`
+                  to=`echo $cmd | cut -d '=' -f 2`
+                  if ! [ "$from" -a "$to" ]; then
+                    echo '[Error]Invalid argument.'
+                    exit 1
+                  fi
+                  sed "s/^$from$/$to/g" $file | sed '/^$/d' > $file-2
                   mv $file-2 $file
-                fi
-                cat $file | xargs
-                sort -u $file -o $file
-                if ! [ "`diff -q $file $file-1`" ]; then
-                  if [[ path != */where/* ]]; then
-                    echo "[Warning]No difference ($file)."
+                else
+                  if [ $mode = '+' ]; then
+                    echo $cmd >> $file
+                  else
+                    sed "s/^$cmd$//g" $file | sed '/^$/d' > $file-2
+                    mv $file-2 $file
                   fi
                 fi
-                rm $file-1
-              done
-              echo
-              ((i++))
-            fi
-          done
-      - name: Modify
-        if: ${{ inputs.ar_command == false }}
-        run: |
-          path='${{ steps.data.outputs.path }}'
-          full_path='${{ steps.data.outputs.full_path }}'
-          change='${{ steps.data.outputs.change }};'
-          i=1
-          if [[ $change = *+* ]] || [[ $change = *-* ]]; then
-            echo '[Error]Invalid syntax.'
-            exit 1
-          fi
-          while ((1==1)); do
-            cmd=`echo $change | cut -d ';' -f $i`
-            if ! [ $cmd ]; then
-              break
-            else
-              if [[ $cmd = /* ]]; then
-                cmd=${cmd:1}
-              fi
-              echo "=== Run ($cmd) ==="
-              if [[ path = */where/* ]]; then
-                path=$full_path
-              fi
-              #############################
-              for file in $path; do
-                from=`echo $cmd | cut -d '=' -f 1`
-                to=`echo $cmd | cut -d '=' -f 2`
-                if [[ $to = /* ]]; then
-                  to=${to:1}
-                fi
-                if ! [ "$from" -a "$to" ]; then
-                  echo '[Error]Invalid argument.'
-                  exit 1
-                fi
-                cp $file $file-1
-                sed "s/^$from$/$to/g" $file | sed '/^$/d' > $file-2
-                mv $file-2 $file
                 cat $file | xargs
                 sort -u $file -o $file
                 if ! [ "`diff -q $file $file-1`" ]; then
